name: MLOps 780 Lambda Container Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configuracao Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-west-2
      
      - name: Build e Push da Imagem Docker
        run: |
          aws ecr create-repository --repository-name mlops-lambda-container780
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{secrets.ACCOUNT_ID}}.dkr.ecr.us-west-2.amazonaws.com
          docker build -t mlops780-lambda-container .
          docker tag mlops780-lambda-container:latest ${{secrets.ACCOUNT_ID}}.dkr.ecr.us-west-2.amazonaws.com/mlops780-lambda-container:latest
          docker push ${{secrets.ACCOUNT_ID}}.dkr.ecr.us-west-2.amazonaws.com/mlops-lambda-container780:latest

      - name: Cria ou Atualiza a função Lambda
        run : |
          aws cloudformation deploy \
            --stack-name mlops780-lambda-container \
            --template-file lambda.yaml \
            --capabilities CAPABILITY_NAMED_IAM
      
